version: "3.9"

services:
  backend:
    image: ghcr.io/winksluizeman/co2tracker-backend:latest
    container_name: co2-backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: ghcr.io/winksluizeman/co2tracker-frontend:latest
    container_name: co2-frontend
    restart: always
    ports:
      - "80:80"

  db:
    image: postgres:16
    container_name: co2-db
    restart: always
    environment:
      POSTGRES_DB: co2tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Appel12
    volumes:
      - db-data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --include-restarting

volumes:
  db-data:
