spring.datasource.url=jdbc:postgresql://localhost:5432/co2tracker
spring.datasource.username=postgres
spring.datasource.password=Appel12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialect niet nodig expliciet bij Hibernate 6, maar mag blijven
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

