name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run tests (JUnit + Testcontainers)
        run: ./gradlew clean test --no-daemon

      - name: Generate JaCoCo coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-reports
          path: build/test-results/test

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test


  sonar-analysis:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info


  build-and-push:
    needs: [build-test, sonar-analysis]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u winksluizeman --password-stdin

      - name: Build backend image
        run: docker build -t ghcr.io/winksluizeman/co2tracker-backend:${{ github.sha }} .

      - name: Push backend image
        run: docker push ghcr.io/winksluizeman/co2tracker-backend:${{ github.sha }}
