name: Quality Pipeline

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  jmeter-test:
    name: Performance Test (JMeter)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: ./gradlew build -x test

      - name: Start backend
        run: |
          nohup java -jar build/libs/*.jar --spring.profiles.active=test &
          sleep 10

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          mv apache-jmeter-5.6.2 jmeter

      - name: Prepare results directory
        run: |
          rm -rf results
          mkdir -p results/report

      - name: Run JMeter testplan
        run: |
          ./jmeter/bin/jmeter \
            -n \
            -t src/tests/performance/testplan.jmx \
            -l results/results.jtl \
            -e -o results/report

      - name: Upload raw results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/results.jtl

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: results/report


  zap-scan:
    name: Security Scan (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: jmeter-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        run: ./gradlew build -x test

      - name: Build backend Docker image
        run: docker build -t backend-app .

      - name: Create Docker network
        run: docker network create zapnet

      - name: Start backend container
        run: docker run -d --network zapnet --name backend backend-app

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://backend:8080"
          cmd_options: "-a"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          artifact_name: "zap_scan"

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
